blank_issues_enabled: false
contact_links:
  - name: I'm unsure where to go
    url: https://github.com/mguyard/appdaemon-coversmanager/discussions
    about: If you are unsure where to go, then joining our community is recommended; Just ask!